import{a as w,S,i as v}from"./assets/vendor-u8rapaCG.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function n(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=n(r);fetch(r.href,o)}})();const $="46322499-d914655ae29712659c6ba744e",q="https://pixabay.com/api/";async function P(e,t=1,n=15){const s=`${q}?key=${$}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${n}`;try{return(await w.get(s)).data}catch(r){throw console.error("Fetching images failed:",r),r}}function C(e){return`
      <a href="${e.largeImageURL}" class="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" data-caption="${e.tags}" />
        <div class="info">
          <p><b>Likes:</b> ${e.likes}</p>
          <p><b>Views:</b> ${e.views}</p>
          <p><b>Comments:</b> ${e.comments}</p>
          <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </a>
    `}function E(e){const t=document.querySelector(".gallery"),n=e.map(C).join("");t.insertAdjacentHTML("beforeend",n),b.refresh()}function I(){document.querySelector(".gallery").innerHTML=""}let l=1;const h=15,M=300;let p;const g=document.querySelector("#search-form"),m=g.querySelector("input"),O=document.querySelector(".loader"),a=document.querySelector(".load-btn"),R=document.querySelector(".gallery"),b=new S(".gallery a",{captions:!0,captionsData:"data-caption",captionDelay:250});let i="",f=!1,c=!1;g.addEventListener("submit",e=>{e.preventDefault(),clearTimeout(p),p=setTimeout(()=>T(),M)});a.addEventListener("click",x);async function T(e){if(i=m.value.trim(),!i)return u("warning","Please enter a search query!");l=1,I(),D(),y(!0),a.style.display="none",await L(i)}async function L(e){if(!c){c=!0;try{const t=await P(e,l,h);if(y(!1),t.hits.length===0)return u("info","Sorry, no images were found for your search query.");E(t.hits),b.refresh(),N(t.totalHits),B(),m.value=""}catch(t){A(t)}finally{c=!1}}}async function x(){c||(a.classList.add("loading"),l+=1,await L(i),a.classList.remove("loading"))}function N(e){const t=e>l*h;a.style.display=t?"block":"none",!t&&!f&&(u("info","We're sorry, but you've reached the end of search results."),f=!0)}function A(e){y(!1),u("error","Something went wrong. Please try again later."),console.error(e)}function y(e){O.style.display=e?"flex":"none"}function u(e,t){v[e]({title:e.charAt(0).toUpperCase()+e.slice(1),message:t})}function B(){const e=R.firstElementChild;if(!e)return;const{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}function D(){f=!1}
//# sourceMappingURL=index.js.map
